// import './01_helloworld'
//import './01_型態'
//import './02_接口'
//import './03_函數類型'
//import './04_類類型'
//import './05_類'
//import './06_繼承'
// import './07_多態'
//import './08_修飾符'
//import './09_readonly修飾符'
// import './10_存取器'
// import './11_靜態成員'
// import './12_抽象類'
// import './13_函數'
// import './14_可選參數'
//import './15_剩餘參數'
//import './16_函數重載'
import './17_泛型'
document.write('Hello Webpack TS!')