// import './01_helloworld'
//import './01_型態'
//import './02_接口'
//import './03_函數類型'
//import './04_類類型'
//import './05_類'
//import './06_繼承'
// import './07_多態'
//import './08_修飾符'
//import './09_readonly修飾符'
// import './10_存取器'
import './11_靜態成員'
document.write('Hello Webpack TS!')